#!/usr/bin/env bash
# Generate the garage-wall background texture candidates for the /revlimiter
# "Hear it" -> trial span (everything hangs on the wall) via OpenAI gpt-image-1.
#
# PROVENANCE NOTE (2026-07-29): both OpenAI keys on Dan's Mac were dead (401),
# so the shipped wall-wood tile was generated by running THESE EXACT PROMPTS
# through Higgsfield nano_banana_pro (1024x1024, 2 credits) instead, then
# post-processed: seam check via 50% roll, feathered cross-fade where a wrap
# edge exceeded 2.5x the interior neighbour delta, and a darkness clamp
# (p99.5 channel <= 0x2e, mean pulled toward #14110d) so the contrast budget
# is guaranteed by construction. This script remains the prompt-of-record and
# works as-is once a live key lands in tools/.openai_key.local.
# Cloned from gen-ui-asset.sh; differs where a TILING BACKGROUND differs from a
# cut-out control: opaque (no transparent background), and the prompts forbid
# directional lighting / vignette / hotspots — the seating light is added in
# CSS so the texture can repeat without visible tiles.
# Output: src/assets/bg/wall-<slug>.png
# Usage:
#   bash tools/gen-wall-texture.sh                 # all three materials
#   bash tools/gen-wall-texture.sh pegboard metal  # subset
set -euo pipefail
cd "$(dirname "$0")/.."

KEY="${OPENAI_API_KEY:-}"
[ -z "$KEY" ] && [ -f tools/.openai_key.local ] && KEY="$(tr -d ' \r\n' < tools/.openai_key.local)"
if [ -z "$KEY" ]; then echo "ERROR: no OpenAI key (set OPENAI_API_KEY or tools/.openai_key.local)"; exit 1; fi

OUT_DIR="src/assets/bg"
mkdir -p "$OUT_DIR"

# Shared wall style. The hard constraints, each there for a reason:
# - near-black: the trial tag's multiply grade and every text contrast number
#   on this span were tuned against --bg-0 #0b0a09; a lighter wall breaks both.
# - perfectly even lighting / no vignette: any baked hotspot repeats with the
#   tile and reads as a grid of spotlights.
# - seamless: it tiles at 768px CSS across every viewport width.
STYLE="Extremely dark, near-black surface, overall tone close to hex #0b0a09 with subtle warm brown-black variation, nothing brighter than a dim mid-grey anywhere. Perfectly even, flat, shadowless lighting across the entire image; no vignette, no light gradient, no hotspot, no glare, no reflections of any environment. Seamlessly tileable texture: the left edge continues the right edge exactly and the top edge continues the bottom edge exactly, with no borders, no frame, and no large one-off features that would repeat visibly. Photographic, fine-grained, worn garage patina; understated, low contrast. No text, no logos, no objects, no hardware, no tools, nothing hanging; surface only, filling the whole frame edge to edge."

PEGBOARD_PROMPT="Photorealistic seamless texture of a dark charcoal-black perforated hardboard pegboard wall, the classic garage tool wall: a regular grid of small round holes, each hole a slightly darker void with a subtle worn rim, hole spacing even and aligned to the frame so the grid tiles cleanly. Surface is aged masonite with faint oil smudges, fine scuffs and dust in the texture. $STYLE"

WOOD_PROMPT="Photorealistic seamless texture of very dark, near-black stained workshop wall planking: vertical wooden boards with subtle worn grain, old filled screw holes and faint tool scuffs, board joints running perfectly vertical and spaced so the pattern tiles cleanly at the frame edges. Aged, oiled, race-shop workbench character. $STYLE"

METAL_PROMPT="Photorealistic seamless texture of a very dark brushed steel wall panel with a fine horizontal brushed grain, faint machine scuffs and a subtle race-shop patina of thin oil films, and a sparse pattern of small flush rivet heads aligned in widely spaced straight rows positioned so they tile cleanly at the frame edges. $STYLE"

gen() {
  local slug="$1" prompt="$2" body resp b64
  echo "[wall-$slug] generating 1536x1024 (high, opaque)..."
  body="$(python3 -c 'import json,sys; print(json.dumps({"model":"gpt-image-1","prompt":sys.argv[1],"size":"1536x1024","quality":"high","output_format":"png","n":1}))' "$prompt")"
  resp="$(curl -s https://api.openai.com/v1/images/generations -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -d "$body")"
  b64="$(python3 -c 'import json,sys; d=json.load(sys.stdin); sys.stdout.write(d["data"][0]["b64_json"]) if d.get("data") else (sys.stderr.write(json.dumps(d)[:900]) or sys.exit(1))' <<<"$resp")"
  python3 -c 'import base64,sys; open(sys.argv[1],"wb").write(base64.b64decode(sys.stdin.read()))' "$OUT_DIR/wall-$slug.png" <<<"$b64"
  echo "[wall-$slug] saved $OUT_DIR/wall-$slug.png ($(wc -c < "$OUT_DIR/wall-$slug.png") bytes)"
}

TARGETS=("$@")
[ ${#TARGETS[@]} -eq 0 ] && TARGETS=(pegboard wood metal)
for t in "${TARGETS[@]}"; do
  case "$t" in
    pegboard) gen pegboard "$PEGBOARD_PROMPT" ;;
    wood)     gen wood     "$WOOD_PROMPT" ;;
    metal)    gen metal    "$METAL_PROMPT" ;;
    *) echo "unknown material: $t (pegboard|wood|metal)"; exit 1 ;;
  esac
done
echo "done."
